### ISSUE TITLE
Major | Danh sách hs | Detail học sinh | Sửa thông tin học sinh

### ISSUE THREAD

**Issue by HanaSE9890** [anhdtqwerty/thpt#109]
Sửa/ thay đổi thông tin học sinh
Step:
1. Click vào học sinh bất kỳ 
2. Chọn Hồ sơ chi tiết -> "Sửa học sinh" 
3. Thay đổi địa chỉ của học sinh 
4. Bấm "Lưu"

Actual:
Lưu không thành công 
"Sửa hồ sơ học sinh" không hiển thị ngày sinh 
Thông báo lỗi "Tạo tài khoản thất bại"
Hiển thị thông tin cũ của học sinh 
Load lại page, không hiển thị thông tin chi tiết về hs
Thoát ra vào lại page, hiển thị lại thông tin, vào xem hồ sơ chi tiết thì vẫn hiển thị thông tin cũ trước khi thay đổi

Expect:
Lưu và hiển thị thành công thông tin học sinh cần sửa

<img width="994" alt="Sửa hs 1" src="https://user-images.githubusercontent.com/82717419/116174944-9e8dce00-a739-11eb-9056-a0bf7ee24498.png">
<img width="1003" alt="Sửa hs 2" src="https://user-images.githubusercontent.com/82717419/116174954-a3528200-a739-11eb-8fdb-33005be8b24d.png">
<img width="996" alt="Sửa hs 3" src="https://user-images.githubusercontent.com/82717419/116174962-a6e60900-a739-11eb-85f4-71c9ce12c7a0.png">
<img width="1011" alt="Sửa hs 4" src="https://user-images.githubusercontent.com/82717419/116174972-a9e0f980-a739-11eb-96d8-808bf67f45cb.png">
<img width="998" alt="Sửa hs 5" src="https://user-images.githubusercontent.com/82717419/116174978-ac435380-a739-11eb-9506-fc9b5da4e027.png">
<img width="1009" alt="Sửa hs 6" src="https://user-images.githubusercontent.com/82717419/116174987-b06f7100-a739-11eb-81b1-9567d8b32aca.png">
<img width="1004" alt="Sửa hs 7" src="https://user-images.githubusercontent.com/82717419/116174999-b402f800-a739-11eb-9417-c70bca0427ce.png">

**Comment by quyngoc** [comment]
@HanaSE9890 

Chị test ảnh hưởng cho em tất cả cả trường khi sửa thông tin học sinh thì dữ liệu liệu mới có hiển thị lên dialog hồ sơ chi tiết không
