### ISSUE TITLE
Danger| Nhập điểm | Bộ lọc | "Môn học" hiển thị không đúng khi chọn lớp 9A0

### ISSUE THREAD

**Issue by HanaSE9890** [anhdtqwerty/thpt#133]
Bộ lọc "Chọn lớp"
Step:
1. Click vào "Chọn lớp" 
2. Nhập lớp 9A0
3. Chọn môn học từ Drop-down list 

Acrual:
Hiển thị các môn học từ Drop-down list thuộc khối lớp 8

Expect:
Hiển thị các môn học thuộc đúng khối lớp 9 từ Drop-down list
<img width="1029" alt="Nhập điểm 3" src="https://user-images.githubusercontent.com/82717419/117327535-e5f42700-aebc-11eb-87d2-d2abc14884f0.png">

**Comment by quyngoc** [comment]
Note: lỗi data
