### ISSUE TITLE
Major | Quản lý khối | Không hiển thị thông tin về tổng số Ban/ Lớp/ Học sinh trong Khối

### ISSUE THREAD

**Issue by HanaSE9890** [anhdtqwerty/thpt#138]
Actual:
Không hiển thị thông tin về tổng tổng số Ban/ Lớp/ Học sinh trong Khối

Expect:
Hiển thị đầy đủ thông tin về tổng số Ban/ Lớp/ Học sinh trong mỗi khối 

<img width="1047" alt="QLK1" src="https://user-images.githubusercontent.com/82717419/117339221-b0a20600-aec9-11eb-928d-53a091606f18.png">

**Comment by quyngoc** [comment]
Không còn quản lý khối
