### ISSUE TITLE
Danger | Môn học | Bộ lọc | Lọc kết hợp "Môn"/ "Khối" + "Phân ban", không hoạt động

### ISSUE THREAD

**Issue by HanaSE9890** [anhdtqwerty/thpt#162]
Lọc kết hợp "Môn"/ "Khối" + "Phân ban"
1. Click chọn lọc "Môn"/ "Khối" + "Phân ban" 
2. Bấm "Lọc"

Actual:
Không hiển thị kết quả

Expect:
Hiển thị kết quả tìm kiếm khi lọc kết hợp 
<img width="1043" alt="Lọc môn 3" src="https://user-images.githubusercontent.com/82717419/117597669-452d9200-b170-11eb-8ffd-02bed30e1507.png">
<img width="1117" alt="Lọc môn 2" src="https://user-images.githubusercontent.com/82717419/117597673-465ebf00-b170-11eb-927e-7ff6940cf414.png">

**Comment by tiendatvn97** [comment]
duplicate #161 issue
